## Universidad Central de Venezuela
## Facultad de Ingeniería
## Escuela de Ingeniería Eléctrica

# <div style="text-align: center"> Sistema de ecuaciones lineales </div>

## <div style="text-align: right"> Periodo 2020-3 </div>
#### <div style="text-align: right"> 19/01/2021  </div>
### <div style="text-align: right"> Prof. Gilberto R. Noguera </div>
#### <div style="text-align: right"> Alumno: José Páez C.I.: 24 311 351 </div>

## Introducción

Los sistemas de ecuaciones lineales nos sirven para resolver diversos problemas, desde los que se presentan en nuestra vida diaria hasta problemas que se presentan en ingeniería, física, matemáticas, economía y otras ciencias. El interés en encontrar la solución a estos sistemas es muy antiguo.

Los sistemas de ecuaciones lineales fueron ya resueltos por los babilonios: utilizaron procedimientos de eliminación de incógnitas en los cuales las llamaban con palabras tales como 'longitud', 'anchura', 'área' o 'volumen', aunque no tuvieran relación con problemas de medida.

También los griegos resolvieron algunos sistemas de ecuaciones y lo hacían mediante métodos geométricos. Thymaridas encontró una fórmula para resolver un determinado sistema de n ecuaciones con n incógnitas. Diophante resuelve problemas de sistemas de ecuaciones, los cuales transforma a una ecuación lineal, él sólo aceptaba soluciones positivas debido a que sólo buscaba resolver problemas y no ecuaciones. Un detalle importante a esta forma de solucionar un sistema es que carece de un método general y en cada problema se deben utilizar métodos excesivamente ingeniosos.

Los sistemas de ecuaciones también se pueden encontrar en documentos indios. No obstante, ellos tampoco lograron obtener métodos generales de resolución, sino que resolvían problemas con tipos especiales de ecuaciones. En el texto chino "El arte matemático", se muestra la solución de problemas de sistemas de ecuaciones usando matrices. Finalmente hasta el siglo XVIII Gauss logra tratar la solución de los sistemas de ecuaciones como un método, capaz de hacer posible la discusión y solución de forma general pudiendo así agrupar los diferentes problemas y su forma de solucionarlos.

## Marco Teórico
###Definición y Caracterización de los SEL.
En matemáticas y álgebra lineal, un sistema de ecuaciones lineales, también conocido como sistema lineal de ecuaciones o simplemente sistema lineal, es un conjunto de ecuaciones lineales (es decir, un sistema de ecuaciones en donde cada ecuación es de primer grado), definidas sobre un cuerpo o un anillo conmutativo. 
En general, un sistema con m ecuaciones lineales y n incógnitas puede ser escrito en forma normal como: 
\begin{matrix}
      a_{11}x_1 & + a_{12}x_2 & + \dots & + a_{1n}x_n & = b_1 \\
      a_{21}x_1 & + a_{22}x_2 & + \dots & + a_{2n}x_n & = b_2 \\
      \dots     & \dots       & \dots   & \dots       & \dots \\
      a_{m1}x_1 & + a_{m2}x_2 & + \dots & + a_{mn}x_n & = b_m
   \end{matrix}
Donde x_1, hasta x_n son las incógnitas y los números a_{ij} E {K} son los coeficientes del sistema sobre el cuerpo 
K {=R,C,...}.

#### Tipos de sistemas lineales
Los sistemas de ecuaciones se pueden clasificar según el número de soluciones que pueden presentar. De acuerdo con ese caso se pueden presentar los siguientes casos:

    Sistema compatible si tiene solución, en este caso además puede distinguirse entre:
   
      Sistema compatible determinado cuando tiene una única solución.
   
      Sistema compatible indeterminado cuando admite un conjunto infinito de soluciones.
   
    Sistema incompatible si no tiene solución.

Quedando así la clasificación:

Los sistemas incompatibles geométricamente se caracterizan por (hiper)planos o rectas que se cruzan sin cortarse. Los sistemas compatibles determinados se caracterizan por un conjunto de (hiper)planos o rectas que se cortan en un único punto. Los sistemas compatibles indeterminados se caracterizan por (hiper)planos que se cortan a lo largo de una recta [o más generalmente un hiperplano de dimensión menor]. Desde un punto de vista algebraico los sistemas compatibles determinados se caracterizan porque el determinante de la matriz es diferente de cero

#### Resolución de sistemas de ecuaciones lineales
Resolver distintos sistemas de ecuaciones es posible gracias a distintos algoritmos. A continuación se presentan algunos:

   a)  Métodos directos: 

  Se denominan métodos directos de resolución de Sistemas de Ecuaciones Lineales, a aquellos que por medio de operaciones elementales entre filas, nos permiten transformar al sistema original en otro de aspecto triangular (Método de Gauss), o diagonal (Método de Gauss - Jordan), de forma tal de poder despejar facilmente los valores de las incógnitas.

 Triangularizacion con máximo pivote por columna: Se busca convertir la matriz en triangular superior Ó inferior (Una sola es suficiente), haciendo uso de la técnica del pivoteo, la cual permite agregar ceros (0) por arriba o debajo de la diagonal principal 

 Factorizaciones PALU: Consiste en transformar la matrices original A en el producto de dos matrices triangulares, una superior y otra inferior, para lo cual ademas podemos permutar la matriz A, multiplicandola por P. 

 Factorización de Cholesky: Cualquier matriz cuadrada A con pivotes no nulos puede ser escrita como el producto de una matriz triangular inferior L y una matriz triangular superior U; esto recibe el nombre de factorización LU (Método PALU sin la permutación). Sin embargo, si A es simétrica y definida positiva, se pueden escoger los factores tales que U es la transpuesta de L.

   b)  Metodos iterativos: 
   
  Son los procesos de aproximaciones sucesivas para resolver sistemas de ecuaciones lineales compatibles determinados. Requieren de la verificación  de  un  criterio  de  convergencia  comúnmente  conocido  como  diagonal  pesada. Se basan en la división de la matriz A, de la forma A=M−N, con M y N matrices adecuadas y M no singular (M se llama precondicionador).

 Jacobi:El método de Jacobi consiste en usar fórmulas como iteración de punto fijo. La base del método consiste en construir una sucesión convergente definida iterativamente. El límite de esta sucesión es precisamente la solución del sistema. A efectos prácticos si el algoritmo se detiene después de un número finito de pasos se llega a una aproximación al valor de x de la solución del sistema. 

 Gauss-Seidel:Aunque este método puede aplicarse a cualquier sistema de ecuaciones lineales que produzca una matriz (cuadrada, naturalmente pues para que exista solución única, el sistema debe tener tantas ecuaciones como incógnitas) de coeficientes con los elementos de su diagonal no-nulos, la convergencia del método solo se garantiza si la matriz es diagonalmente dominante o si es simétrica y, a la vez, definida positiva. 

 SOR: Este método se basan en una técnica que intenta mejorar la convergencia del método de Gauss Seidel mediante el refinamiento de la aproximación actual. La relación representa una ligera modificacion del metodo de gauss-seidel y esta permite mejorar la convergencia en algunos casos. Despues de que se calcula cada nuevo valor de x, ese valor se modifica mediante un promedio ponderado de los resultados de las iteraciones anterior y actual.


## Práctica
1)Se procede a construir un sistema generando una matriz aleatoria de orden 20

In [1]:
import numpy as np

X = np.random.rand(20,20)
X = X * 10
print(X)

[[1.05585339 1.00920058 5.48804148 1.332864   0.8669239  1.12135396
  5.67479275 6.56794875 9.6976494  1.25813502 7.5758961  8.68090519
  3.34062537 4.51940064 6.19479724 9.62658657 3.73797638 3.07836782
  5.79156122 7.02694476]
 [8.820074   5.28074876 4.51784531 9.0921492  2.95480718 7.47128898
  7.65044446 3.32570348 0.24291079 9.30291106 4.40174063 6.01377783
  7.08758545 2.31738286 0.09827122 5.45896845 4.70246791 1.11009209
  1.00663585 5.02240957]
 [3.68772947 4.10481659 1.49447016 7.10267766 6.25239944 1.52513333
  4.56232031 3.83673965 9.88092525 9.30776045 2.52592402 4.81286554
  3.14933671 7.17185587 8.41708253 4.71142049 7.84808504 8.79580417
  2.60627538 3.19234817]
 [7.45880118 3.44722469 3.13949216 1.19169217 8.63762741 1.26810952
  7.3979647  5.63002009 6.84573538 5.56930701 9.02944841 3.11534911
  0.97097864 6.17200307 6.08917271 8.38028817 6.59831542 2.89059487
  7.76868602 5.33602733]
 [4.75940599 8.67675957 4.21865982 8.22531025 7.81741922 0.09428752
  9.46853578 0.2

Análisis: Se construye, con base al generador de numeros aleatorios (entre cero y uno) incluido en el modulo de numpy, una matriz 20x20, y se multiplica por 10 para que los valores esten entre 0 y 10.

2)Se construye y resuelve el sistema Ax=b, donde: la diagonal principal son 3, los elementos inmediatamente debajo de la diagonal son 2 e inmediatamente arriba de la diagonal -2, :


In [6]:
import numpy as np
Dim=20

A = np.zeros((Dim,Dim))
for i in range(Dim-1):
    A[i][i]=3
    A[i][i+1]=2
    A[i][i-1]=-2
A[Dim-1][Dim-1]=3
A[Dim-1][Dim-2]=-2
print (A)

[[ 3.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -2.]
 [-2.  3.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -2.  3.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -2.  3.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -2.  3.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -2.  3.  2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -2.  3.  2.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -2.  3.  2.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -2.  3.  2.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -2.  3.  2.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -2.  3.  2.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -2.  3.  2.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -2.  3.  2.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -2.  3.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -2.  3.]]


3) Metodos Iterativos:

Método de Jacobi:

In [1]:
from math import *
from pprint import pprint
import numpy as np


def distinf(x, y):
    return max([abs(x[i]-y[i]) for i in range(len(x))])

def Jacobi(A, b, x0, TOL, MAX):
    n = len(A)
    x = [0.0 for x in range(n)]
    k = 1
    while k <= MAX:
        for i in range(n):
            if abs(A[i][i]) <= 1e-15:
                print(" Imposible iterar ")
                return
            s = sum([A[i][j]*x0[j] for j in range(n) if j != i])
            x[i] = (b[i]-float(s))/float(A[i][i])
        pprint(x)
        if distinf(x, x0) < TOL:
            print (r" Solucion encontrada ")
            return
        k += 1
        for i in range(n):
            x0[i] = x[i]
    print(" Iteraciones agotadas ")
    return

Método de Gauss-Seidel:

In [6]:
import numpy as np
import math

def gaussSeidel(A,x,tol = 1.0e-9):
    omega = 1.0
    k=10
    p=1
    for i in range(1,501):
            xOld = x.copy()
            x = A(x,omega)
            dx = math.sqrt(np.dot(x-xOld,x-xOld))
            if dx < tol: return x,i,omega
        # Computar el factor de relajación despues de k+p iteraciones
            if i == k: dx1 = dx
            if i==k+p:
                    dx2 = dx
                    omega = 2.0/(1.0 + math.sqrt(1.0  \
                        - (dx2/dx1)**(1.0/p)))
    print("Gauss-Seidel falló en converger")

## Referencias

ANÁLISIS NUMÉRICO. Autores: Richard L. Burden, Douglas J. Faires,  Annette M. Burden

Matemáticas para Ingeniería. Autores: Diego Ovalle, Miguel Bernal, Jaime Posada.

Numerical Methods in Engineering . Autor: Jaan Kiusalaas

http://campusvirtual.cua.uam.mx/material/tallerm/18_Problemas_De_Sistemas_De_Ecuaciones_html/index.html

https://es.wikipedia.org/wiki/Sistema_de_ecuaciones_lineales

http://www3.fi.mdp.edu.ar/analisis/temas/met_dir/metDir.htm

https://www.ingenieria.unam.mx/pinilla/PE105117/pdfs/tema3/3-3_metodos_jacobi_gauss-seidel.pdf

http://repobib.ubiobio.cl/jspui/bitstream/123456789/1228/1/Burgos_Alarcon_Dario.pdf

https://es.wikipedia.org/wiki/M%C3%A9todo_de_Jacobi

https://es.wikipedia.org/wiki/M%C3%A9todo_de_Gauss-Seidel

https://sites.google.com/site/procesosnumericoszagarra20131/practica-2/metodo-iterativo-de-sor



https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.rand.html

https://stackoverflow.com/questions/13347559/create-empty-matrix-python

